from django.db import models

class Extracted(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

# Create your models here.
class Kitco(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

class SilverBullion(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

class IndigoPrecious(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

class BullionStar(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

class GoldCentral(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

class Apmex(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)

class SDBullion(models.Model):
    product_name = models.TextField()
    price_usd = models.CharField(max_length=10)
    price_sgd = models.CharField(max_length=10)
    crypto_price = models.CharField(max_length=10)
    paypal_price = models.CharField(max_length=10)
    weight = models.CharField(max_length=10)
    premium = models.FloatField()
    product_id = models.CharField(max_length=10)
    metal_content = models.CharField(max_length=20)
    stock = models.CharField(max_length=10)
    purity = models.CharField(max_length=10)
    manufacture = models.CharField(max_length=20)
    product_url = models.CharField(max_length=50)
    supplier_name = models.CharField(max_length=20)
    supplier_country = models.CharField(max_length=20)
