# Generated by Django 4.0.4 on 2022-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_scrap', '0003_alter_apmex_premium_alter_bullionstar_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracted',
            name='premium',
            field=models.CharField(default=2.0, max_length=10),
            preserve_default=False,
        ),
    ]
