# Generated by Django 4.0.4 on 2022-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_scrap', '0004_extracted_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracted',
            name='stock',
            field=models.CharField(default='In Stock', max_length=10),
            preserve_default=False,
        ),
    ]
